### PR TITLE
Add lens jig from Kisolre

### PR DESCRIPTION
**Pull request by tareko**
Add lens jig from Kisolre

### CODE REVIEW

**Comment by tareko** [comment]
@0penBrain : I requested a review from you as well. Are you willing to do this? If so, I'll add you to a few more. If not, then not a problem obviously!

tarek : )

**Comment by 0penBrain** [comment]
@tareko : yes I can review others' models (but to be fair I'd like mine to be also ;) ). But in no case you should lock the merging process for that. Firstly my spare time in mainly uncertain, and secondly I'm not an expert of GitHub and may miss things. :)

**Comment by 0penBrain** [comment]
Review of the file :
- Modeling method : OK (robustness, maintainability, ...)
- Geometry check : OK (with BOP)
- Original part matching : OK (deviation < 50 µm)

Very minor remarks about modeling : 
- Sketch001 + Sketch003 : use only 2 dimensions + constant thickness of 4 mm instead
- If the 2 jigs shall have same width, maybe both bodies could be linked with expressions

Remarks about file : 
- I wonder if it's a good thing to have both jigs in the same file. When it will be time to assemble parts together, it can be a mess if the 2 parts have their relative positions locked
- There are 4 solids in the file that were very probably derived from the original part mesh import. In my models I removed them before submitting so the file only contains the new FreeCAD model, but I'm not sure what is right... Could you decide on that point @tareko ?

**Comment by mef51** [comment]
Will review this when we test assembly

**Pull request merged**
