### PR TITLE
button holder bottom initial release

### PR DESCRIPTION
**Pull request by 0penBrain**
button holder bottom FreeCAD model

### CODE REVIEW

**Comment by 0penBrain** [comment]
@tareko : Ouch. According FC forum, seems this is a duplicate of a model already done by @eddriesen... :/
Feel free to reject this PR. Sorry for noise.

**Comment by tareko** [comment]
Correct, but I don't see where @eddriesen's version of it ended up, since it doesn't look like it's any PR either.

**Comment by eddriesen** [comment]
> 
> 
> Correct, but I don't see where @eddriesen's version of it ended up, since it doesn't look like it's any PR either.

I'm back home , I did a pull req a few days ago of that file.... Don't mind looking at the construction method of an experienced Freecadder. ;) *heading to 0penbrain's repo*

**Comment by 0penBrain** [comment]
@eddriesen : I see only one PR from you on the repo (handle coupler part). Maybe something goes wrong with this part when you PRed... :/

**Comment by eddriesen** [comment]
Mea culpa; Must of switched the WIP / Done part... Will get back to finishing some more models asap.
If you prefer, you can add yours, and I will take on another / Do some tweaks you suggested .
(Back from holidays , giant " must do first" backlog ;) )

**Review by mef51 — APPROVED** [review]

**Pull request merged**
