### PR TITLE
Handle_coupler

### PR DESCRIPTION
**Pull request by eddriesen**
drawn in partdesign bench, withoutany bleedingedge features.

### CODE REVIEW

**Comment by 0penBrain** [comment]
Hi, had a very quick review. Some remarks in case it may help :
- ears could be a bit closer from original with 2x 9.35mm diam. circles spaced by 21.2 mm
- in cavity, the "clogs" can be closer represented if tangency constraints are removed and things constrained a bit differently
- cavity uses external geometry. This isn't recommended for robustness (in this model it even triggers an error due to unsupported constraint). Here it isn't really needed to use it. You can just use an arc with a bigger radius. ;)
- Fillet is also subject to toponaming issues. In this case, I would have model the fillet in the cavity sketch directly.
- on nibs, 0.3 mm dim. could be reduced to 0.2 mm

All in all, it should reduce deviation from original part below 100 µm. ;)

**Comment by tareko** [comment]
@eddriesen and @Frankie-E4Rdesigns : Would you like to respond to @0penBrain's comments? I believe he's referencing [this tutorial on how to compare parts](https://forum.freecadweb.org/viewtopic.php?p=330227#p330227).

**Comment by 0penBrain** [comment]
@tareko : I actually used same method as in the tutorial up to step 5. Then I open the sketches and so can visually compare original part and model, eventually using [ViewSection feature](https://www.freecadweb.org/wiki/Sketcher_ViewSection) to have a section view. ;)
Some remarks also concern model robustness (due to some FC limitations) but community can easily deals with that in the future if needed.
Anyway, feel free to take or let this comments. :)

**Comment by eddriesen** [comment]
> 
> 
> Hi, had a very quick review. Some remarks in case it may help :
> 
>     * ears could be a bit closer from original with 2x 9.35mm diam. circles spaced by 21.2 mm
> 
>     * in cavity, the "clogs" can be closer represented if tangency constraints are removed and things constrained a bit differently
> 
>     * cavity uses external geometry. This isn't recommended for robustness (in this model it even triggers an error due to unsupported constraint). Here it isn't really needed to use it. You can just use an arc with a bigger radius. ;)
> 
>     * Fillet is also subject to toponaming issues. In this case, I would have model the fillet in the cavity sketch directly.
> 
>     * on nibs, 0.3 mm dim. could be reduced to 0.2 mm
> 
> 
> All in all, it should reduce deviation from original part below 100 µm. ;)

Thanks, I'll check this out today or tomorrow!

**Pull request closed without merging**
